from django.contrib import admin
from django.urls import path
from app import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path("login/", v.login, name="login"),
    path("", v.logout, name="logout"),
    path("inicio/",v.inicio,name="inicio"),
    path("crearUsuario/", v.crearUsuario, name="crearUsuario"),
    path("perfilusuario/", v.perfilusuario, name="perfilusuario"),
    path("customizarpc/", v.customizarpc, name="customizar"),
    path("sobrenosotros/", v.sobrenosotros, name="sobrenosotros"),
    path('api/placas-compatible-con/<int:procesador_id>/', v.placas_compatibles),
    path("api/rams-compatible-con/<int:placa_id>/", v.rams_compatibles),
    path("api/gpus-compatible-con/<int:placa_id>/", v.gpus_compatibles),
    path("api/almacenamientos-compatible-con/<int:placa_id>/", v.almacenamientos_compatibles),
    path("api/gabinetes-compatible-con/<int:placa_id>/", v.gabinetes_compatibles),
    path("api/fuentes-compatible-con/<int:gpu_id>/", v.fuentes_compatibles),
    path("api/coolers-compatible-con/<int:procesador_id>/", v.coolers_compatibles),
    path('editar_cotizacion/<int:pk>/', v.actualizar_cotizacion, name='editar_cotizacion'),
    path('eliminar_cotizacion/<int:cotizacion_id>/', v.eliminar_cotizacion, name='eliminar_cotizacion'),
    path('admin-panel/', v.panel_admin, name='panel_admin'),
    path('adminprocesador/', v.procesador_admin, name='adminprocesador'),
    path('admintarjetagrafica/', v.tarjeta_grafica_admin, name='admintarjetagrafica'),
    path('buscarprocesador/', v.buscar_procesador, name='buscarprocesador'),
    path('eliminarprocesador/', v.eliminar_procesador, name='eliminarprocesador'),
    path('eliminarprocesador/<int:pk>/', v.eliminar_procesador_confirmado, name='eliminarprocesador_confirmado'),
    path('editarprocesador/', v.editar_procesador, name='editarprocesador'),
    path('editarprocesador/<int:id>/', v.editarprocesador_confirmado, name='editarprocesador_confirmado'),
    path('placamadre/', v.placamadre_admin, name='adminplacamadre'),
    path('buscarplacamadre/', v.buscar_placamadre, name='buscarplacamadre'),
    path('eliminarplacamadre/', v.eliminar_placamadre, name='eliminarplacamadre'),
    path('eliminarplacamadre/<int:pk>/', v.eliminar_placamadre_confirmado, name='eliminarplacamadre_confirmado'),
    path('editarplacamadre/', v.editar_placamadre, name='editarplacamadre'),
    path('editarplacamadre/<int:id>/', v.editarplacamadre_confirmado, name='editarplacamadre_confirmado'),
    path('buscartarjetagrafica/', v.buscar_tarjetagrafica, name='buscartarjetagrafica'),
    path('editartarjetagrafica/', v.editar_tarjetagrafica, name='editartarjetagrafica'),
    path('editartarjetagrafica/<int:id>/', v.editar_tarjetagrafica_confirmado, name='editartarjetagrafica_confirmado'),
    path('eliminartarjetagrafica/', v.eliminar_tarjetagrafica, name='eliminartarjetagrafica'),
    path('eliminartarjetagrafica/<int:pk>/', v.eliminar_tarjetagrafica_confirmado, name='eliminartarjetagrafica_confirmado'),
    path('admingabinete/', v.gabinete_admin, name='admingabinete'),
    path('buscargabinete/', v.buscar_gabinete, name='buscargabinete'),
    path('editargabinete/', v.editar_gabinete, name='editargabinete'),
    path('editargabinete/<int:id>/', v.editar_gabinete_confirmado, name='editargabinete_confirmado'),
    path('eliminargabinete/', v.eliminar_gabinete, name='eliminargabinete'),
    path('eliminargabinete/<int:pk>/', v.eliminar_gabinete_confirmado, name='eliminargabinete_confirmado'),
]
