# Generated by Django 5.1.7 on 2025-05-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='pais',
            field=models.CharField(max_length=25),
        ),
    ]
