# Generated by Django 4.2 on 2025-06-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cotizacion_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjetagrafica',
            name='fuentes_compatibles',
        ),
        migrations.AlterField(
            model_name='procesador',
            name='modelo',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
