# Generated by Django 4.2 on 2025-06-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_tarjetagrafica_fuentes_compatibles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetagrafica',
            name='vram',
            field=models.CharField(max_length=20),
        ),
    ]
