# Generated by Django 4.2 on 2025-06-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_tarjetagrafica_vram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesador',
            name='fabricante',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='procesador',
            name='modelo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
